from __future__ import annotations

import os
import subprocess
from dataclasses import replace
from pathlib import Path
from types import MappingProxyType

import pytest

from agent_stack.release.errors import LifecycleFailure
from agent_stack.release.first_install import (
    canonical_first_install_command_digest,
    render_canonical_first_install_shell,
    render_release_body,
)
from agent_stack.release.identity import ReleaseIdentity
from agent_stack.release.manifest import VerifiedRelease
from agent_stack.release import gates


def _release(**wheel_overrides: object) -> VerifiedRelease:
    version = "0.1.5"
    wheel = {
        "name": f"agent_workflow_pack-{version}-py3-none-any.whl",
        "url": (
            "https://github.com/swl007007/agent-workflow-pack/releases/download/"
            f"v{version}/agent_workflow_pack-{version}-py3-none-any.whl"
        ),
        "size": 10,
        "sha256": "a" * 64,
        **wheel_overrides,
    }
    return VerifiedRelease(
        identity=ReleaseIdentity(
            "github.com/swl007007/agent-workflow-pack", "agent-workflow-pack", version
        ),
        manifest_digest="b" * 64,
        source_commit="c" * 40,
        bundles=MappingProxyType({}),
        assets=MappingProxyType(
            {
                "wheel": MappingProxyType(wheel),
                "sdist": MappingProxyType(
                    {
                        "name": f"agent_workflow_pack-{version}.tar.gz",
                        "url": "https://github.com/swl007007/agent-workflow-pack/releases/"
                        f"download/v{version}/agent_workflow_pack-{version}.tar.gz",
                        "size": 10,
                        "sha256": "d" * 64,
                    }
                ),
            }
        ),
        immutable_release=True,
    )


def test_renderer_binds_exact_manifest_wheel_and_is_deterministic(tmp_path: Path) -> None:
    release = _release()
    first = render_canonical_first_install_shell(release, release.manifest_digest)
    old = Path.cwd()
    try:
        os.chdir(tmp_path)
        os.environ["UV_INDEX"] = "https://evil.invalid/simple"
        second = render_canonical_first_install_shell(release, release.manifest_digest)
    finally:
        os.chdir(old)
        os.environ.pop("UV_INDEX", None)

    assert first == second
    assert str(release.assets["wheel"]["url"]) in first
    assert str(release.assets["wheel"]["sha256"]) in first
    assert release.manifest_digest in first
    assert "--isolated --no-config --no-env-file --no-index" in first
    assert "--no-sources --no-build --no-python-downloads" in first
    assert subprocess.run(["sh", "-n"], input=first, text=True, check=False).returncode == 0


def test_manifest_or_wheel_change_changes_rendered_bytes() -> None:
    release = _release()
    baseline = render_canonical_first_install_shell(release, release.manifest_digest)
    changed_manifest = replace(release, manifest_digest="e" * 64)
    assert (
        render_canonical_first_install_shell(
            changed_manifest, changed_manifest.manifest_digest
        )
        != baseline
    )
    changed = _release(sha256="f" * 64)
    assert render_canonical_first_install_shell(changed, changed.manifest_digest) != baseline


@pytest.mark.parametrize(
    "release,digest",
    [
        (_release(url="http://github.com/evil.whl"), "b" * 64),
        (_release(url="https://evil.invalid/pkg.whl"), "b" * 64),
        (_release(url="https://github.com/swl007007/agent-workflow-pack/releases/download/v0.1.4/x.whl"), "b" * 64),
        (_release(sha256="not-a-hash"), "b" * 64),
        (_release(url="https://github.com/swl007007/agent-workflow-pack/releases/download/v0.1.5/x.whl\nwhoami"), "b" * 64),
        (_release(), "placeholder"),
    ],
)
def test_renderer_rejects_untrusted_or_shell_unsafe_authority(
    release: VerifiedRelease, digest: str
) -> None:
    with pytest.raises(LifecycleFailure, match="canonical first-install"):
        render_canonical_first_install_shell(release, digest)


def test_release_body_is_complete_deterministic_projection() -> None:
    release = _release()
    body = render_release_body(release, release.manifest_digest)
    command = render_canonical_first_install_shell(release, release.manifest_digest)

    assert body == render_release_body(release, release.manifest_digest)
    assert "<!-- generated by agent-workflow-pack; do not edit -->" in body
    assert f"```sh\n{command}```" in body
    assert release.source_commit in body
    assert str(release.assets["wheel"]["sha256"]) in body
    assert str(release.assets["sdist"]["sha256"]) in body
    assert release.manifest_digest in body
    assert canonical_first_install_command_digest(command) == __import__(
        "hashlib"
    ).sha256(command.encode()).hexdigest()


def test_release_gate_registry_includes_canonical_first_install_publication() -> None:
    assert "canonical-first-install-publication" in gates._GATE_IDS
    assert len(gates._GATE_IDS) == 14
